version: "3.8"


x-common-variables: &common-env-variables
  POSTGRES_PASSWORD: qVZGZ2qV98O
  POSTGRES_DB: flats_sell
  POSTGRES_USER: admin


services:
  app:
    build: .
    command: python flats_downloader/server.py
    environment:
      <<: *common-env-variables
      COUNT: 500
      DB_TABLE_NAME: sreality_flats_sell
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432  # should be same as second port in "database" service
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - database
    network_mode: "host"


  database:
    image: postgres
    environment:
      <<: *common-env-variables
    ports:
      - 5455:5432
    network_mode: "host"
