version: "3.8"


x-common-variables: &common-env-variables
  POSTGRES_PASSWORD: qVZGZ2qV98O
  POSTGRES_DB: flats_sell
  POSTGRES_USER: admin


services:
  app:
    build: .
    # Run server
    command: python flats_downloader/server.py
    # Download newest flats
    # command: bash -c "cd flats_downloader && scrapy crawl flats"
    environment:
      <<: *common-env-variables
      COUNT: 500
      DB_TABLE_NAME: sreality_flats_sell
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432  # should be same as second port in "database" service
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - database
    network_mode: "host"


  database:
    image: postgres
    environment:
      <<: *common-env-variables
#      PGDATA: "./pgdata"
    ports:
      - 5455:5432
#    volumes:
#     - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    network_mode: "host"
