version: "3.8"


x-common-variables: &common-env-variables
  POSTGRES_PASSWORD: qVZGZ2qV98O
  POSTGRES_DB: flats_sell
  POSTGRES_USER: admin


services:
  app:
    build: .
    #image: flats:app
    #command: bash -c "sleep 10 && python flats_downloader/server.py"  # wait for database to start
    command: python flats_downloader/server.py
    environment:
      <<: *common-env-variables
      COUNT: 500
      DB_TABLE_NAME: sreality_flats_sell
      #POSTGRES_HOST: database  # should be same as the name of the other service
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432  # should be same as second port in "database" service
      #POSTGRES_DB: flats_sell
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - database
    network_mode: "host"


  database:
    image: postgres
    environment:   # Set up postgres database name and password
      <<: *common-env-variables
      PGDATA: "./pgdata"
    ports:    # Set up ports exposed for other containers to connect to
      - 5455:5432  # outside:inside ports
    #networks:
    #  - app-tier
    volumes:
     - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    network_mode: "host"
